<!DOCTYPE html>
<html>

<head>
	<meta charset='UTF-8' /> 
	<meta name='description' content='' />
	<meta name='robots' content='noodp, noydir' />
	<meta name='viewport' content='width=device-width, initial-scale=1' />
	<meta id="timeStampFormat" name="timeStampFormat" content='MMM d, yyyy hh:mm:ss a'/>
	
	<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600' rel='stylesheet' type='text/css' />
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
	<link href='https://cdn.rawgit.com/extent-framework/extent-github-cdn/191775216e8ce53c38791eb07a1d2f31d0ae11b5/v3html/css/extent.css' type='text/css' rel='stylesheet' />
	
	<title>GAPI project</title>

	<style type='text/css'>
		/* json-tree */
		.jstBracket,.jstComma,.jstValue{white-space:pre-wrap}.jstValue{font-size:10px;font-weight:400;font-family:"Lucida Console",Monaco,monospace}.jstProperty{color:#666;word-wrap:break-word}.jstBool{color:#2525CC}.jstNum{color:#D036D0}.jstNull{color:gray}.jstStr{color:#2DB669}.jstFold:after{content:' -';cursor:pointer}.jstExpand{white-space:normal}.jstExpand:after{content:' +';cursor:pointer}.jstFolded{white-space:normal!important}.jstHiddenBlock{display:none}
			
            
                
            
        
	</style>
	
	<script type="text/javascript">
		/*! json-tree - v0.2.2 - 2017-09-25, MIT LICENSE */
		var JSONTree=function(){var n={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;","/":"&#x2F;"},t=0,r=0;this.create=function(n,t){return r+=1,N(u(n,0,!1),{class:"jstValue"})};var e=function(t){return t.replace(/[&<>'"]/g,function(t){return n[t]})},s=function(){return r+"_"+t++},u=function(n,t,r){if(null===n)return f(r?t:0);switch(typeof n){case"boolean":return l(n,r?t:0);case"number":return i(n,r?t:0);case"string":return o(n,r?t:0);default:return n instanceof Array?a(n,t,r):c(n,t,r)}},c=function(n,t,r){var e=s(),u=Object.keys(n).map(function(r){return j(r,n[r],t+1,!0)}).join(m()),c=[g("{",r?t:0,e),N(u,{id:e}),p("}",t)].join("\n");return N(c,{})},a=function(n,t,r){var e=s(),c=n.map(function(n){return u(n,t+1,!0)}).join(m());return[g("[",r?t:0,e),N(c,{id:e}),p("]",t)].join("\n")},o=function(n,t){var r=e(JSON.stringify(n));return N(v(r,t),{class:"jstStr"})},i=function(n,t){return N(v(n,t),{class:"jstNum"})},l=function(n,t){return N(v(n,t),{class:"jstBool"})},f=function(n){return N(v("null",n),{class:"jstNull"})},j=function(n,t,r){var s=v(e(JSON.stringify(n))+": ",r),c=N(u(t,r,!1),{});return N(s+c,{class:"jstProperty"})},m=function(){return N(",\n",{class:"jstComma"})},N=function(n,t){return d("span",t,n)},d=function(n,t,r){return"<"+n+Object.keys(t).map(function(n){return" "+n+'="'+t[n]+'"'}).join("")+">"+r+"</"+n+">"},g=function(n,t,r){return N(v(n,t),{class:"jstBracket"})+N("",{class:"jstFold",onclick:"JSONTree.toggle('"+r+"')"})};this.toggle=function(n){var t=document.getElementById(n),r=t.parentNode,e=t.previousElementSibling;""===t.className?(t.className="jstHiddenBlock",r.className="jstFolded",e.className="jstExpand"):(t.className="",r.className="",e.className="jstFold")};var p=function(n,t){return N(v(n,t),{})},v=function(n,t){return Array(2*t+1).join(" ")+n};return this}();
	</script>
</head>
	<body class='extent dark default hide-overflow '>
		<div id='theme-selector' alt='Click to toggle theme. To enable by default, use theme configuration.' title='Click to toggle theme. To enable by default, use theme configuration.'>
			<span><i class='material-icons'>desktop_windows</i></span>
		</div>
<nav>
	<div class="nav-wrapper">
		<a href="#!" class="brand-logo black"><img src="https://cdn.rawgit.com/extent-framework/extent-github-cdn/d74480e/commons/img/logo.png"></a>
		<!-- slideout menu -->
		<ul id='slide-out' class='side-nav fixed hide-on-med-and-down'>
			<li class='waves-effect active'><a href='#!' view='test-view' onclick="configureView(0);chartsView('test');"><i class='material-icons'>dashboard</i></a></li>
						<li class='waves-effect'><a href='#!' onclick="configureView(-1);chartsView('dashboard');" view='dashboard-view'><i class='material-icons'>track_changes</i></a></li>
		</ul>
		<!-- report name -->
		<span class='report-name'>API Functional Test Automation Report</span>
		<!-- report headline -->
		<span class='report-headline'></span>
		<!-- nav-right -->
		<ul id='nav-mobile' class='right hide-on-med-and-down nav-right'>
			<a href='#!'>
			<span class='label blue darken-3 suite-start-time'>Mar 20, 2023 04:06:45 PM</span>
			</a>
		</ul>
	</div>
</nav>		<!-- container -->
		<div class='container'>
<div id='test-view' class='view'>
	<section id='controls'>
		<div class='controls grey lighten-4'>
			<!-- test toggle -->
			<div class='chip transparent'>
				<a class='dropdown-button tests-toggle' data-activates='tests-toggle' data-constrainwidth='true' data-beloworigin='true' data-hover='true' href='#'>
				<i class='material-icons'>warning</i> Status
				</a>
				<ul id='tests-toggle' class='dropdown-content'>
										<li status='pass'><a href='#!'>Pass <i class='material-icons green-text'>check_circle</i></a></li>
					<li status='fail'><a href='#!'>Fail <i class='material-icons red-text'>cancel</i></a></li>
					<li class='divider'></li>
					<li status='clear' clear='true'><a href='#!'>Clear Filters <i class='material-icons'>clear</i></a></li>
				</ul>
			</div>
			<!-- test toggle -->
			<!-- category toggle -->
			<!-- category toggle -->
			<!-- clear filters -->
			<div class='chip transparent hide'>
				<a class='' id='clear-filters' alt='Clear Filters' title='Clear Filters'>
				<i class='material-icons'>close</i> Clear
				</a>
			</div>
			<!-- clear filters -->
			<!-- enable dashboard -->
			<div id='toggle-test-view-charts' class='chip transparent'>
				<a class='pink-text' id='enable-dashboard' alt='Enable Dashboard' title='Enable Dashboard'>
				<i class='material-icons'>track_changes</i> Dashboard
				</a>
			</div>
			<!-- enable dashboard -->
			<!-- search -->
			<div class='chip transparent' alt='Search Tests' title='Search Tests'>
				<a href="#" class='search-div'>
				<i class='material-icons'>search</i> Search
				</a>
				<div class='input-field left hide'>
					<input id='search-tests' type='text' class='validate browser-default' placeholder='Search Tests...'>
				</div>
			</div>
			<!-- search -->
		</div>
	</section>
<div id='test-view-charts' class='subview-full'>
	<div id='charts-row' class='row nm-v nm-h'>
		<div class='col s12 m6 l6 np-h'>
			<div class='card-panel nm-v'>
				<div class='left panel-name'>Tests</div>
				<div class='chart-box' style="max-height:94px;">
					<canvas id='parent-analysis' width='100' height='80'></canvas>
				</div>
				<div class='block text-small'>
					<span class='tooltipped' data-position='top' data-tooltip='4.545%'><span class='strong'>1</span> test(s) passed</span>
				</div>
				<div class='block text-small'>
					<span class='strong tooltipped' data-position='top' data-tooltip='95.455%'>21</span> test(s) failed, <span class='strong tooltipped' data-position='top' data-tooltip='0%'>0</span> others
				</div>
			</div>
		</div>
	</div>
	<div id="timeline-chart" class="row nm-v nm-h">
		<div class="col s12 m12 l12 np-h">
			<div class="card-panel">
				<div class='left panel-name'>Timeline (seconds)</div>
				<div class="chart-box" style="width:98%;max-height:145px;">
					<canvas id="timeline" height="120"></canvas>
				</div>
			</div>
		</div>
	</div>
</div>	<div class='subview-left left'>
		<div class='view-summary'>
			<ul id='test-collection' class='test-collection'>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='1'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket With Request Type as Planned Work and category as Existing cross connect or connectivity testing</span>
						<span class='test-time'>Mar 20, 2023 04:06:48 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:48 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:49 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+803ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:48 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:49 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:49 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='2'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket  With Request Type as Planned Work and Category as Dedicated escort</span>
						<span class='test-time'>Mar 20, 2023 04:06:49 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:49 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:49 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+651ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:49 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:49 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:49 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='3'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket With Request Type as Planned Work and  Category as Customer premise cabling</span>
						<span class='test-time'>Mar 20, 2023 04:06:49 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:49 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:50 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+535ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:50 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:50 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:50 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='4'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket With RequestType as Planned  Work and Category as Auditing</span>
						<span class='test-time'>Mar 20, 2023 04:06:50 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:50 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:50 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+530ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:50 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:50 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:50 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='5'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket with Request Type as Planned Work and Category as Tape swaps</span>
						<span class='test-time'>Mar 20, 2023 04:06:50 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:50 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:51 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+489ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:51 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:51 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:51 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='6'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket with Request Type as Planned Work and Category as Equipment de-installation</span>
						<span class='test-time'>Mar 20, 2023 04:06:51 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:51 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:51 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+472ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:51 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:51 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:51 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='7'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket with Request Type as Planned Work and Category as Equipment installation</span>
						<span class='test-time'>Mar 20, 2023 04:06:51 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:51 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:52 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+594ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:52 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:52 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:52 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='8'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket with Request Type as Planned Work and Category as Other</span>
						<span class='test-time'>Mar 20, 2023 04:06:52 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:52 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:52 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+534ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:52 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:52 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:52 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='9'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Request With RequestType as Urgent Work and Category as Existing cross connect or connectivity testing</span>
						<span class='test-time'>Mar 20, 2023 04:06:52 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:52 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:53 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+482ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:53 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:53 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:53 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='10'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Request With RequestType asUrgent Work and Category as Equipment troubleshoot or replacement</span>
						<span class='test-time'>Mar 20, 2023 04:06:53 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:53 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:53 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+502ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:53 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:53 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:53 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='11'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Request With RequestType as Urgent Work and Category as KVM (keyboard, video, mouse) assistance</span>
						<span class='test-time'>Mar 20, 2023 04:06:53 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:53 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:54 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+474ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:54 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:54 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:54 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='12'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket With RequestType as Urgent Work and Category as Power cycle or reboot</span>
						<span class='test-time'>Mar 20, 2023 04:06:54 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:54 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:54 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+480ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:54 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:54 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:54 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='13'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket with Request Type as Urgent Work and Category as Other</span>
						<span class='test-time'>Mar 20, 2023 04:06:54 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:54 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:55 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+528ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:55 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:55 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:55 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='14'>
					<div class='test-heading'>
						<span class='test-name'>Verify Create Remote Hands Ticket with Request Type as Planned Work but Without Category</span>
						<span class='test-time'>Mar 20, 2023 04:06:55 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:55 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:55 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+282ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='pass'>
				<td class='status pass' title='pass' alt='pass'><i class='material-icons'>check_circle</i></td>
				<td class='timestamp'>4:06:55 PM</td>
				<td class='step-details'>
						Response Status Code and Status Message is HTTP/1.1 400 Bad Request
					
				</td>
			</tr>
			<tr class='log' status='pass'>
				<td class='status pass' title='pass' alt='pass'><i class='material-icons'>check_circle</i></td>
				<td class='timestamp'>4:06:55 PM</td>
				<td class='step-details'>
						Error Response message is {"ErrorWrapper":{"Errors":{"Error":{"Error":{"Source":"remotehands-service","ReasonCode":"MISMATCH_CATEGORY_REQUESTTYPE","Description":"Payload 'category' has an unexpected value for the given 'requestType'","Recoverable":"false","Details":"constraintField : ValidWorkTypeCategory.createRemoteHandsRequest ,correlationid : 55a8bc5d-5136-4d9b-9f5b-664f8bc7f718"}}}}}
					
				</td>
			</tr>
			<tr class='log' status='pass'>
				<td class='status pass' title='pass' alt='pass'><i class='material-icons'>check_circle</i></td>
				<td class='timestamp'>4:06:55 PM</td>
				<td class='step-details'>
						Not allowed to create Remote Hands request
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:55 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.utilities.TestUtilities.verifyErrorfromResponseMessage(TestUtilities.java:561)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:71)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:55 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [client] but found [MISMATCH_CATEGORY_REQUESTTYPE]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:55 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='15'>
					<div class='test-heading'>
						<span class='test-name'>Verify Create Remote Hands Ticket with Request Type as Urgent Work but Without Category</span>
						<span class='test-time'>Mar 20, 2023 04:06:55 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:55 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:55 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+271ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='pass'>
				<td class='status pass' title='pass' alt='pass'><i class='material-icons'>check_circle</i></td>
				<td class='timestamp'>4:06:55 PM</td>
				<td class='step-details'>
						Response Status Code and Status Message is HTTP/1.1 400 Bad Request
					
				</td>
			</tr>
			<tr class='log' status='pass'>
				<td class='status pass' title='pass' alt='pass'><i class='material-icons'>check_circle</i></td>
				<td class='timestamp'>4:06:55 PM</td>
				<td class='step-details'>
						Error Response message is 
                {
                    "error":{
                        "correlationId":"a7a4d604-95c8-4553-9cfe-1a174576a622",
                        "type":"client",
                        "message":"Payload 'category' has an unexpected value for the given 'requestType'"
                    }
                }
					
				</td>
			</tr>
			<tr class='log' status='pass'>
				<td class='status pass' title='pass' alt='pass'><i class='material-icons'>check_circle</i></td>
				<td class='timestamp'>4:06:55 PM</td>
				<td class='step-details'>
						Not allowed to create Remote Hands request
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:55 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.json.JSONObject.get(JSONObject.java:580)<br> org.json.JSONObject.getJSONObject(JSONObject.java:790)<br> com.gapi.utilities.TestUtilities.verifyErrorfromResponseMessage(TestUtilities.java:555)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:71)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:55 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>org.json.JSONException: JSONObject["ErrorWrapper"] not found.Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:55 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='16'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket with only Mandatory Parameters</span>
						<span class='test-time'>Mar 20, 2023 04:06:55 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:55 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:56 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+497ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:56 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:56 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:56 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='17'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket With Location Optional Parameter</span>
						<span class='test-time'>Mar 20, 2023 04:06:56 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:56 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:56 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+470ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:56 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> jdk.internal.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:56 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:56 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='18'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket With Customer Reference Optional Parameter</span>
						<span class='test-time'>Mar 20, 2023 04:06:56 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:56 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:57 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+496ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:57 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> jdk.internal.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:57 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:57 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='19'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket with One Notification Recipient Optional Parameter</span>
						<span class='test-time'>Mar 20, 2023 04:06:57 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:57 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:57 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+475ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:57 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> jdk.internal.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:57 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:57 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='20'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket with Multiple Notification Recipient Optional Parameter</span>
						<span class='test-time'>Mar 20, 2023 04:06:57 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:57 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:58 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+478ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:58 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> jdk.internal.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:58 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:58 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  pass' status='pass' bdd='false' test-id='21'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket with Invalid Email Format In Notification Recipient</span>
						<span class='test-time'>Mar 20, 2023 04:06:58 PM</span>
						<span class='test-status right pass'>pass</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:58 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:58 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+269ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='pass'>
				<td class='status pass' title='pass' alt='pass'><i class='material-icons'>check_circle</i></td>
				<td class='timestamp'>4:06:58 PM</td>
				<td class='step-details'>
						Response Status Code and Status Message is HTTP/1.1 400 Bad Request
					
				</td>
			</tr>
			<tr class='log' status='pass'>
				<td class='status pass' title='pass' alt='pass'><i class='material-icons'>check_circle</i></td>
				<td class='timestamp'>4:06:58 PM</td>
				<td class='step-details'>
						Error Response message is {"ErrorWrapper":{"Errors":{"Error":{"Error":{"Source":"remotehands-service","ReasonCode":"INVALID_NOTIFICATION_RECIPIENTS","Description":"Payload 'notificationRecipients' has an invalid email.","Recoverable":"false","Details":"constraintField : Pattern.createRemoteHandsRequest.notificationRecipients ,correlationid : 5cbc79f2-10df-4bf0-9e2d-7807cb57ef5e"}}}}}
					
				</td>
			</tr>
			<tr class='log' status='pass'>
				<td class='status pass' title='pass' alt='pass'><i class='material-icons'>check_circle</i></td>
				<td class='timestamp'>4:06:58 PM</td>
				<td class='step-details'>
						Not allowed to create Remote Hands request
					
				</td>
			</tr>
			<tr class='log' status='pass'>
				<td class='status pass' title='pass' alt='pass'><i class='material-icons'>check_circle</i></td>
				<td class='timestamp'>4:06:58 PM</td>
				<td class='step-details'>
						<span class='badge white-text green'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
				<li class='test displayed active  fail' status='fail' bdd='false' test-id='22'>
					<div class='test-heading'>
						<span class='test-name'>Create Remote Hands Ticket With Reference Ticket Optional Parameter</span>
						<span class='test-time'>Mar 20, 2023 04:06:58 PM</span>
						<span class='test-status right fail'>fail</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Mar 20, 2023 04:06:58 PM</span>
	<span class='label end-time'>Mar 20, 2023 04:06:59 PM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+476ms</span>
</div>
<div class='test-steps'>
	<table class='bordered table-results'>
		<thead>
			<tr>
				<th>Status</th>
				<th>Timestamp</th>
				<th>Details</th>
			</tr>
		</thead>
		<tbody>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:59 PM</td>
				<td class='step-details'>
						<details><summary><b><font color = red>Exception Occured, Click to see details:</font></b></summary>[org.testng.Assert.fail(Assert.java:99)<br> org.testng.Assert.failNotEquals(Assert.java:1037)<br> org.testng.Assert.assertEqualsImpl(Assert.java:140)<br> org.testng.Assert.assertEquals(Assert.java:122)<br> org.testng.Assert.assertEquals(Assert.java:629)<br> org.testng.Assert.assertEquals(Assert.java:639)<br> com.gapi.testCases.CreateRemoteHandsTicket.verifyCreateRemoteHandsTicket(CreateRemoteHandsTicket.java:51)<br> jdk.internal.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:568)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:59 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>java.lang.AssertionError: expected [201] but found [401]Test Failed</span>
					
				</td>
			</tr>
			<tr class='log' status='fail'>
				<td class='status fail' title='fail' alt='fail'><i class='material-icons'>cancel</i></td>
				<td class='timestamp'>4:06:59 PM</td>
				<td class='step-details'>
						<span class='badge white-text red'>verifyCreateRemoteHandsTicket</span>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
					</div>
				</li>
			</ul>
		</div>
	</div>
	<!-- subview left -->
	<div class='subview-right left'>
		<div class='view-summary'>
			<h5 class='test-name'></h5>
			<div id='step-filters' class="right">
				<span class="blue-text" status="info" alt="info" title="info"><i class="material-icons">info_outline</i></span>
				<span class="green-text" status="pass" alt="pass" title="pass"><i class="material-icons">check_circle</i></span>
				<span class="red-text" status="fail" alt="fail" title="fail"><i class="material-icons">cancel</i></span>
				<span class="red-text text-darken-4" status="fatal" alt="fatal" title="fatal"><i class="material-icons">cancel</i></span>
				<span class="pink-text text-lighten-1" status="error" alt="error" title="error"><i class="material-icons">error</i></span>
				<span class="orange-text" alt="warning" status="warning" title="warning"><i class="material-icons">warning</i></span>
				<span class="teal-text" status="skip" alt="skip" title="skip"><i class="material-icons">redo</i></span>
				<span status="clear" alt="Clear filters" title="Clear filters"><i class="material-icons">clear</i></span>
			</div>
		</div>
	</div>
	<!-- subview right -->
</div>
<!-- test view --><!-- category view --><!-- exception view --><div id='dashboard-view' class='view hide'>
	<div class='card-panel transparent np-v'>
		<h5>Dashboard</h5>

		<div class='row'>
			<div class='col s2'>
				<div class='card-panel r'>
					Tests
					<div class='panel-lead'>22</div>
				</div>
			</div>
			<div class='col s2'>
				<div class='card-panel r'>
					Steps
					<div class='panel-lead'>0</div>
				</div>
			</div>
			<div class='col s2'>
				<div class='card-panel r'>
					Start
					<div class='panel-lead'>Mar 20, 2023 04:06:45 PM</div>
				</div>
			</div>
			<div class='col s2'>
				<div class='card-panel r'>
			 		End
			 		<div class='panel-lead'>Mar 20, 2023 04:06:45 PM</div>
				</div>
			</div>
			<div class='col s2'>
				<div class='card-panel r'>
					Time Taken
					<div class='panel-lead'>0h 0m 0s+0ms</div>
				</div>
			</div>
			<div class='col s4'>
				<div class='card-panel dashboard-environment'>
					<span class='right label cyan white-text'>Environment</span><p>&nbsp;</p>
					
					<table>
						<tr>
							<th>Name</th>
							<th>Value</th>
						</tr>
							<tr>
								<td>Environemnt</td>
								<td>TEST</td>
							</tr>
							<tr>
								<td>user</td>
								<td>Ramu Kasi</td>
							</tr>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- dashboard view -->
<!-- testrunner-logs view -->		</div>
		<!-- container -->
		<script>
			var statusGroup = {
				passParent: 1,
				failParent: 21,
				fatalParent: 0,
				errorParent: 0,
				warningParent: 0,
				skipParent: 0,
				exceptionsParent: 21,
				
				passChild: 0,
				failChild: 0,
				fatalChild: 0,
				errorChild: 0,
				warningChild: 0,
				skipChild: 0,
				infoChild: 0,
				debugChild: 0,
				exceptionsChild: 0,
				
				passGrandChild: 0,
				failGrandChild: 0,
				fatalGrandChild: 0,
				errorGrandChild: 0,
				warningGrandChild: 0,
				skipGrandChild: 0,
				infoGrandChild: 0,
				debugGrandChild: 0,
				exceptionsGrandChild: 0,
			};
		</script>
		<script>
			var timeline = {
			        "Create Remote Hands Ticket With Request Type as Planned Work and category as Existing cross connect or connectivity testing":0.803,"Create Remote Hands Ticket  With Request Type as Planned Work and Category as Dedicated escort":0.651,"Create Remote Hands Ticket With Request Type as Planned Work and  Category as Customer premise cabling":0.535,"Create Remote Hands Ticket With RequestType as Planned  Work and Category as Auditing":0.53,"Create Remote Hands Ticket with Request Type as Planned Work and Category as Tape swaps":0.489,"Create Remote Hands Ticket with Request Type as Planned Work and Category as Equipment de-installation":0.472,"Create Remote Hands Ticket with Request Type as Planned Work and Category as Equipment installation":0.594,"Create Remote Hands Ticket with Request Type as Planned Work and Category as Other":0.534,"Create Remote Hands Request With RequestType as Urgent Work and Category as Existing cross connect or connectivity testing":0.482,"Create Remote Hands Request With RequestType asUrgent Work and Category as Equipment troubleshoot or replacement":0.502,"Create Remote Hands Request With RequestType as Urgent Work and Category as KVM (keyboard, video, mouse) assistance":0.474,"Create Remote Hands Ticket With RequestType as Urgent Work and Category as Power cycle or reboot":0.48,"Create Remote Hands Ticket with Request Type as Urgent Work and Category as Other":0.528,"Verify Create Remote Hands Ticket with Request Type as Planned Work but Without Category":0.282,"Verify Create Remote Hands Ticket with Request Type as Urgent Work but Without Category":0.271,"Create Remote Hands Ticket with only Mandatory Parameters":0.497,"Create Remote Hands Ticket With Location Optional Parameter":0.47,"Create Remote Hands Ticket With Customer Reference Optional Parameter":0.496,"Create Remote Hands Ticket with One Notification Recipient Optional Parameter":0.475,"Create Remote Hands Ticket with Multiple Notification Recipient Optional Parameter":0.478,"Create Remote Hands Ticket with Invalid Email Format In Notification Recipient":0.269,"Create Remote Hands Ticket With Reference Ticket Optional Parameter":0.476
			};
		</script>
		<script src='https://cdn.rawgit.com/extent-framework/extent-github-cdn/master/v3html/js/extent.js' type='text/javascript'></script>
		<script type='text/javascript'>
			
            
                $(document).ready(function() {
                    
                });
            
        
		</script>
	</body>
</html>